version: '3'

services:
  redis:
    container_name: mapdagu-redis
    hostname: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      mapdagu_network:
        - ipv4_address: 172.18.0.2

  springboot:
    container_name: spring-dev
    image: koeyhk/mapdagu:latest-dev
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      SPRING_PROFILES_ACTIVE : dev-env # 사용할 profile 지정
    networks:
      - mapdagu_network

networks:
  mapdagu_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16